package com.wiseside.martinidev.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Accasamento implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Accasamento() {
    }




}